version: '3'
services:
  marqo-os:
    image: "marqoai/marqo-os:0.0.3"
    ports:
    - "9200:9200"
    - "9600:9600"
    environment:
      - discovery.type=single-node
    healthcheck:
     test: ["CMD-SHELL", "curl -X GET 'https://marqo-os:9200/_cluster/health' --insecure -H 'Content-Type: application/json' -u admin:admin >/dev/null || exit 1"]
     interval: 5s
     timeout: 3s
     retries: 50
  marqo:
    image: "marqoai/marqo:latest"
    ports:
    - "8882:8882"
    environment: 
      OPENSEARCH_URL: "https://marqo-os:9200"
    depends_on:
      marqo-os:
        condition: service_healthy

